if (room > room0)
{
    audio_stop_all();
    ini_open("Save5.ini");
    obj_controller.save = 5;
    ds_grid_read(obj_stat_holder.irving_stats, ini_read_string("Characters", 0, "Null"));
    ds_grid_read(obj_stat_holder.garrick_stats, ini_read_string("Characters", 1, "Null"));
    ds_grid_read(obj_stat_holder.alden_stats, ini_read_string("Characters", 2, "Null"));
    ds_grid_read(obj_stat_holder.maren_stats, ini_read_string("Characters", 3, "Null"));
    ds_grid_read(obj_stat_holder.elias_stats, ini_read_string("Characters", 4, "Null"));
    ds_grid_read(obj_stat_holder.cia_stats, ini_read_string("Characters", 5, "Null"));
    ds_grid_read(obj_stat_holder.alexa_stats, ini_read_string("Characters", 6, "Null"));
    ds_grid_read(obj_stat_holder.lincoln_stats, ini_read_string("Characters", 7, "Null"));
    ds_grid_read(obj_stat_holder.sophia_stats, ini_read_string("Characters", 8, "Null"));
    ds_grid_read(obj_stat_holder.sloane_stats, ini_read_string("Characters", 9, "Null"));
    ds_grid_read(obj_stat_holder.corvan_stats, ini_read_string("Characters", 10, "Null"));
    ds_grid_read(obj_stat_holder.sara_stats, ini_read_string("Characters", 11, "Null"));
    ds_grid_read(obj_stat_holder.samara_stats, ini_read_string("Characters", 12, "Null"));
    ds_grid_read(obj_stat_holder.brooke_stats, ini_read_string("Characters", 13, "Null"));
    ds_grid_read(obj_stat_holder.bianca_stats, ini_read_string("Characters", 14, "Null"));
    ds_grid_read(obj_stat_holder.monroe_stats, ini_read_string("Characters", 15, "Null"));
    ds_grid_read(obj_stat_holder.benji_stats, ini_read_string("Characters", 16, "Null"));
    ds_grid_read(obj_stat_holder.caius_stats, ini_read_string("Characters", 17, "Null"));
    ds_grid_read(obj_stat_holder.vesta_stats, ini_read_string("Characters", 18, "Null"));
    ds_grid_read(obj_stat_holder.iris_stats, ini_read_string("Characters", 19, "Null"));
    ds_grid_read(obj_stat_holder.faust_stats, ini_read_string("Characters", 20, "Null"));
    ds_grid_read(obj_stat_holder.ford_stats, ini_read_string("Characters", 21, "Null"));
    ds_grid_read(obj_stat_holder.kitara_stats, ini_read_string("Characters", 22, "Null"));
    ds_grid_read(obj_stat_holder.thaelanel_stats, ini_read_string("Characters", 23, "Null"));
    ds_grid_read(obj_stat_holder.fenton_stats, ini_read_string("Characters", 24, "Null"));
    ds_grid_read(obj_stat_holder.wren_stats, ini_read_string("Characters", 25, "Null"));
    ds_grid_read(obj_stat_holder.rose_stats, ini_read_string("Characters", 26, "Null"));
    ds_grid_read(obj_stat_holder.aurima_stats, ini_read_string("Characters", 27, "Null"));
    ds_grid_read(obj_stat_holder.liberty_stats, ini_read_string("Characters", 28, "Null"));
    ds_grid_read(obj_stat_holder.helena_stats, ini_read_string("Characters", 29, "Null"));
    ds_grid_read(obj_storage_holder.item_storage, ini_read_string("Storage", 1, "Null"));
    ds_grid_read(obj_game_data.data, ini_read_string("Game Data", 0, "Null"));
    ds_grid_read(obj_game_data.characters, ini_read_string("Game Data", 3, "Null"));
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Irving"), 3, 1119);
    
    if (ini_read_real("Game Data", "1", 0) > 81)
        ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Irving"), 3, 1122);
    
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Irving"), 0, 38);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Irving"), 1, 290);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Garrick"), 3, 1084);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Garrick"), 0, 41);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Garrick"), 1, 292);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Maren"), 3, 1088);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Maren"), 0, 45);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Maren"), 1, 294);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Alden"), 3, 1127);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Alden"), 0, 43);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Alden"), 1, 293);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Cia"), 3, 1097);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Cia"), 0, 49);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Cia"), 1, 296);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Elias"), 3, 1103);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Elias"), 0, 47);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Elias"), 1, 297);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Lincoln"), 3, 1093);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Lincoln"), 0, 51);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Lincoln"), 1, 298);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Bianca"), 3, 1175);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Bianca"), 0, 53);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Bianca"), 1, 299);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sophia"), 3, 1100);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sophia"), 0, 55);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sophia"), 1, 301);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sloane"), 3, 1134);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sloane"), 0, 57);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sloane"), 1, 300);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Brooke"), 3, 1178);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Brooke"), 0, 74);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Brooke"), 1, 302);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Benji"), 3, 1117);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Benji"), 0, 79);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Benji"), 1, 303);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Caius"), 3, 1167);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Caius"), 0, 81);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Caius"), 1, 304);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sara"), 3, 1170);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sara"), 0, 61);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Sara"), 1, 305);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Samara"), 3, 1199);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Samara"), 0, 65);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Samara"), 1, 295);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Corvan"), 3, 1143);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Corvan"), 0, 68);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Corvan"), 1, 307);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Helena"), 3, 1206);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Helena"), 0, 72);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Helena"), 1, 320);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Aurima"), 3, 1137);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Aurima"), 0, 100);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Aurima"), 1, 308);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Vesta"), 3, 1192);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Vesta"), 0, 83);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Vesta"), 1, 306);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Monroe"), 3, 1114);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Monroe"), 0, 77);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Monroe"), 1, 310);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Ford"), 3, 1125);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Ford"), 0, 88);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Ford"), 1, 309);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Iris"), 3, 1148);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Iris"), 0, 86);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Iris"), 1, 311);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Maeve"), 3, 1131);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Maeve"), 0, 94);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Maeve"), 1, 313);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Thae'Lanel"), 3, 1202);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Thae'Lanel"), 0, 102);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Thae'Lanel"), 1, 314);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Wren"), 3, 1184);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Wren"), 0, 90);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Wren"), 1, 312);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Faust"), 3, 1187);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Faust"), 0, 93);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Faust"), 1, 315);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Fenton"), 3, 1164);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Fenton"), 0, 98);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Fenton"), 1, 316);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Alexa"), 3, 1140);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Alexa"), 0, 70);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Alexa"), 1, 318);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Rose"), 3, 1172);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Rose"), 0, 96);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Rose"), 1, 317);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Liberty"), 3, 1181);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Liberty"), 0, 59);
    ds_grid_set(obj_game_data.characters, ds_grid_value_x(obj_game_data.characters, 0, 0, 29, 5, "Liberty"), 1, 319);
    
    if (ini_read_real("Save Flag", "1", 0) == 0)
        room_goto(scr_level_select(ini_read_real("Game Data", "1", 0)));
    else if (ini_read_real("Save Flag", "1", 0) == 1)
        room_goto(ini_read_real("Game Data", "1", 0) - room_scene_7_1);
    else
        room_goto(ini_read_real("Game Data", "1", 0));
    
    ini_close();
    global.difficulty = ds_grid_get(obj_game_data.data, 0, 4);
    global.deathsetting = ds_grid_get(obj_game_data.data, 0, 5);
    global.gametime = ds_grid_get(obj_game_data.data, 0, 14);
    global.enemyhp = ds_grid_get(obj_game_data.data, 2, 6);
    global.enemystr = ds_grid_get(obj_game_data.data, 2, 7);
    global.enemymag = ds_grid_get(obj_game_data.data, 2, 8);
    global.enemydef = ds_grid_get(obj_game_data.data, 2, 9);
    global.enemyfor = ds_grid_get(obj_game_data.data, 2, 10);
    global.enemydex = ds_grid_get(obj_game_data.data, 2, 11);
    global.enemymas = ds_grid_get(obj_game_data.data, 2, 12);
    global.enemyspd = ds_grid_get(obj_game_data.data, 2, 13);
    global.enemylck = ds_grid_get(obj_game_data.data, 2, 14);
    global.randomenemyaptitudes = ds_grid_get(obj_game_data.data, 2, 5);
    global.randomclassaptitudes = ds_grid_get(obj_game_data.data, 1, 11);
    
    if (global.randomclassaptitudes == 1)
    {
        with (obj_game_data)
        {
            random_set_seed(ds_grid_get(obj_game_data.data, 1, 12));
            
            for (ii = 0; ii <= 54; ii += 1)
                ds_list_add(classvalues, random_range(0, 50), random_range(0, 50), random_range(0, 50), random_range(0, 50), random_range(0, 50), random_range(0, 50), random_range(0, 50), random_range(0, 50), random_range(0, 50));
            
            randomize();
        }
    }
    
    global.randombases = ds_grid_get(obj_game_data.data, 1, 2);
    global.randomgoldmodifier = ds_grid_get(obj_game_data.data, 1, 3);
    global.randomXPmodifier = ds_grid_get(obj_game_data.data, 1, 4);
    global.linearlevels = ds_grid_get(obj_game_data.data, 1, 5);
    global.randomclasses = ds_grid_get(obj_game_data.data, 1, 6);
    global.randomspells = ds_grid_get(obj_game_data.data, 1, 8);
    global.randomweapons = ds_grid_get(obj_game_data.data, 1, 9);
    global.randomitems = ds_grid_get(obj_game_data.data, 1, 10);
    
    with (obj_stat_holder)
    {
        ds_grid_set(irving_stats, 7, 0, "Garrick");
        ds_grid_set(irving_stats, 7, 1, "Maren");
        ds_grid_set(irving_stats, 7, 2, "Alden");
        ds_grid_set(irving_stats, 7, 3, "Cia");
        ds_grid_set(irving_stats, 7, 4, "Elias");
        ds_grid_set(irving_stats, 7, 5, "Lincoln");
        ds_grid_set(irving_stats, 7, 6, "Sloane");
        ds_grid_set(irving_stats, 7, 7, "Sara");
        ds_grid_set(irving_stats, 7, 8, "Vesta");
        ds_grid_set(irving_stats, 7, 9, "Liberty");
        ds_grid_set(garrick_stats, 7, 0, "Irving");
        ds_grid_set(garrick_stats, 7, 1, "Maren");
        ds_grid_set(garrick_stats, 7, 2, "Alden");
        ds_grid_set(garrick_stats, 7, 3, "Cia");
        ds_grid_set(garrick_stats, 7, 4, "Lincoln");
        ds_grid_set(garrick_stats, 7, 5, "Sloane");
        ds_grid_set(garrick_stats, 7, 6, "Benji");
        ds_grid_set(garrick_stats, 7, 7, "Ford");
        ds_grid_set(garrick_stats, 7, 8, "Wren");
        ds_grid_set(garrick_stats, 7, 9, "Faust");
        ds_grid_set(kitara_stats, 7, 0, "Alden");
        ds_grid_set(kitara_stats, 7, 1, "Lincoln");
        ds_grid_set(kitara_stats, 7, 2, "Corvan");
        ds_grid_set(kitara_stats, 7, 3, "Vesta");
        ds_grid_set(kitara_stats, 7, 4, "Thae'Lanel");
        ds_grid_set(kitara_stats, 7, 5, "Wren");
        ds_grid_set(kitara_stats, 7, 6, "Fenton");
        ds_grid_set(kitara_stats, 7, 7, "Rose");
        ds_grid_set(kitara_stats, 7, 8, "Alexa");
        ds_grid_set(kitara_stats, 7, 9, "Liberty");
        ds_grid_set(cia_stats, 7, 0, "Irving");
        ds_grid_set(cia_stats, 7, 1, "Garrick");
        ds_grid_set(cia_stats, 7, 2, "Elias");
        ds_grid_set(cia_stats, 7, 3, "Bianca");
        ds_grid_set(cia_stats, 7, 4, "Brooke");
        ds_grid_set(cia_stats, 7, 5, "Caius");
        ds_grid_set(cia_stats, 7, 6, "Helena");
        ds_grid_set(cia_stats, 7, 7, "Monroe");
        ds_grid_set(cia_stats, 7, 8, "Fenton");
        ds_grid_set(cia_stats, 7, 9, "Alexa");
        ds_grid_set(corvan_stats, 7, 0, "Maren");
        ds_grid_set(corvan_stats, 7, 1, "Alden");
        ds_grid_set(corvan_stats, 7, 2, "Sara");
        ds_grid_set(corvan_stats, 7, 3, "Samara");
        ds_grid_set(corvan_stats, 7, 4, "Aurima");
        ds_grid_set(corvan_stats, 7, 5, "Vesta");
        ds_grid_set(corvan_stats, 7, 6, "Maeve");
        ds_grid_set(corvan_stats, 7, 7, "Thae'Lanel");
        ds_grid_set(corvan_stats, 7, 8, "Fenton");
        ds_grid_set(corvan_stats, 7, 9, "Liberty");
        ds_grid_set(elias_stats, 7, 0, "Irving");
        ds_grid_set(elias_stats, 7, 1, "Maren");
        ds_grid_set(elias_stats, 7, 2, "Cia");
        ds_grid_set(elias_stats, 7, 3, "Samara");
        ds_grid_set(elias_stats, 7, 4, "Helena");
        ds_grid_set(elias_stats, 7, 5, "Vesta");
        ds_grid_set(elias_stats, 7, 6, "Ford");
        ds_grid_set(elias_stats, 7, 7, "Iris");
        ds_grid_set(elias_stats, 7, 8, "Thae'Lanel");
        ds_grid_set(elias_stats, 7, 9, "Rose");
        ds_grid_set(aurima_stats, 7, 0, "Alden");
        ds_grid_set(aurima_stats, 7, 1, "Benji");
        ds_grid_set(aurima_stats, 7, 2, "Caius");
        ds_grid_set(aurima_stats, 7, 3, "Sara");
        ds_grid_set(aurima_stats, 7, 4, "Samara");
        ds_grid_set(aurima_stats, 7, 5, "Corvan");
        ds_grid_set(aurima_stats, 7, 6, "Helena");
        ds_grid_set(aurima_stats, 7, 7, "Vesta");
        ds_grid_set(aurima_stats, 7, 8, "Thae'Lanel");
        ds_grid_set(aurima_stats, 7, 9, "Liberty");
        ds_grid_set(monroe_stats, 7, 0, "Cia");
        ds_grid_set(monroe_stats, 7, 1, "Bianca");
        ds_grid_set(monroe_stats, 7, 2, "Sophia");
        ds_grid_set(monroe_stats, 7, 3, "Sloane");
        ds_grid_set(monroe_stats, 7, 4, "Brooke");
        ds_grid_set(monroe_stats, 7, 5, "Ford");
        ds_grid_set(monroe_stats, 7, 6, "Iris");
        ds_grid_set(monroe_stats, 7, 7, "Faust");
        ds_grid_set(monroe_stats, 7, 8, "Rose");
        ds_grid_set(monroe_stats, 7, 9, "Alexa");
        ds_grid_set(alden_stats, 7, 0, "Irving");
        ds_grid_set(alden_stats, 7, 1, "Garrick");
        ds_grid_set(alden_stats, 7, 2, "Maren");
        ds_grid_set(alden_stats, 7, 3, "Sophia");
        ds_grid_set(alden_stats, 7, 4, "Brooke");
        ds_grid_set(alden_stats, 7, 5, "Corvan");
        ds_grid_set(alden_stats, 7, 6, "Aurima");
        ds_grid_set(alden_stats, 7, 7, "Maeve");
        ds_grid_set(alden_stats, 7, 8, "Faust");
        ds_grid_set(alden_stats, 7, 9, "Fenton");
        ds_grid_set(sloane_stats, 7, 0, "Irving");
        ds_grid_set(sloane_stats, 7, 1, "Garrick");
        ds_grid_set(sloane_stats, 7, 2, "Sophia");
        ds_grid_set(sloane_stats, 7, 3, "Brooke");
        ds_grid_set(sloane_stats, 7, 4, "Benji");
        ds_grid_set(sloane_stats, 7, 5, "Sara");
        ds_grid_set(sloane_stats, 7, 6, "Monroe");
        ds_grid_set(sloane_stats, 7, 7, "Thae'Lanel");
        ds_grid_set(sloane_stats, 7, 8, "Faust");
        ds_grid_set(sloane_stats, 7, 9, "Fenton");
        ds_grid_set(maren_stats, 7, 0, "Irving");
        ds_grid_set(maren_stats, 7, 1, "Garrick");
        ds_grid_set(maren_stats, 7, 2, "Alden");
        ds_grid_set(maren_stats, 7, 3, "Elias");
        ds_grid_set(maren_stats, 7, 4, "Benji");
        ds_grid_set(maren_stats, 7, 5, "Samara");
        ds_grid_set(maren_stats, 7, 6, "Corvan");
        ds_grid_set(maren_stats, 7, 7, "Helena");
        ds_grid_set(maren_stats, 7, 8, "Ford");
        ds_grid_set(maren_stats, 7, 9, "Iris");
        ds_grid_set(benji_stats, 7, 0, "Garrick");
        ds_grid_set(benji_stats, 7, 1, "Maren");
        ds_grid_set(benji_stats, 7, 2, "Bianca");
        ds_grid_set(benji_stats, 7, 3, "Sophia");
        ds_grid_set(benji_stats, 7, 4, "Sloane");
        ds_grid_set(benji_stats, 7, 5, "Brooke");
        ds_grid_set(benji_stats, 7, 6, "Caius");
        ds_grid_set(benji_stats, 7, 7, "Aurima");
        ds_grid_set(benji_stats, 7, 8, "Faust");
        ds_grid_set(benji_stats, 7, 9, "Fenton");
        ds_grid_set(ford_stats, 7, 0, "Garrick");
        ds_grid_set(ford_stats, 7, 1, "Maren");
        ds_grid_set(ford_stats, 7, 2, "Elias");
        ds_grid_set(ford_stats, 7, 3, "Brooke");
        ds_grid_set(ford_stats, 7, 4, "Samara");
        ds_grid_set(ford_stats, 7, 5, "Vesta");
        ds_grid_set(ford_stats, 7, 6, "Monroe");
        ds_grid_set(ford_stats, 7, 7, "Thae'Lanel");
        ds_grid_set(ford_stats, 7, 8, "Fenton");
        ds_grid_set(ford_stats, 7, 9, "Liberty");
        ds_grid_set(fenton_stats, 7, 0, "Alden");
        ds_grid_set(fenton_stats, 7, 1, "Cia");
        ds_grid_set(fenton_stats, 7, 2, "Lincoln");
        ds_grid_set(fenton_stats, 7, 3, "Sophia");
        ds_grid_set(fenton_stats, 7, 4, "Sloane");
        ds_grid_set(fenton_stats, 7, 5, "Benji");
        ds_grid_set(fenton_stats, 7, 6, "Corvan");
        ds_grid_set(fenton_stats, 7, 7, "Ford");
        ds_grid_set(fenton_stats, 7, 8, "Maeve");
        ds_grid_set(fenton_stats, 7, 9, "Faust");
        ds_grid_set(caius_stats, 7, 0, "Cia");
        ds_grid_set(caius_stats, 7, 1, "Bianca");
        ds_grid_set(caius_stats, 7, 2, "Sophia");
        ds_grid_set(caius_stats, 7, 3, "Benji");
        ds_grid_set(caius_stats, 7, 4, "Sara");
        ds_grid_set(caius_stats, 7, 5, "Helena");
        ds_grid_set(caius_stats, 7, 6, "Aurima");
        ds_grid_set(caius_stats, 7, 7, "Iris");
        ds_grid_set(caius_stats, 7, 8, "Wren");
        ds_grid_set(caius_stats, 7, 9, "Rose");
        ds_grid_set(rose_stats, 7, 0, "Elias");
        ds_grid_set(rose_stats, 7, 1, "Sophia");
        ds_grid_set(rose_stats, 7, 2, "Caius");
        ds_grid_set(rose_stats, 7, 3, "Helena");
        ds_grid_set(rose_stats, 7, 4, "Monroe");
        ds_grid_set(rose_stats, 7, 5, "Iris");
        ds_grid_set(rose_stats, 7, 6, "Maeve");
        ds_grid_set(rose_stats, 7, 7, "Wren");
        ds_grid_set(rose_stats, 7, 8, "Faust");
        ds_grid_set(rose_stats, 7, 9, "Alexa");
        ds_grid_set(bianca_stats, 7, 0, "Cia");
        ds_grid_set(bianca_stats, 7, 1, "Lincoln");
        ds_grid_set(bianca_stats, 7, 2, "Sophia");
        ds_grid_set(bianca_stats, 7, 3, "Benji");
        ds_grid_set(bianca_stats, 7, 4, "Caius");
        ds_grid_set(bianca_stats, 7, 5, "Samara");
        ds_grid_set(bianca_stats, 7, 6, "Monroe");
        ds_grid_set(bianca_stats, 7, 7, "Iris");
        ds_grid_set(bianca_stats, 7, 8, "Wren");
        ds_grid_set(bianca_stats, 7, 9, "Alexa");
        ds_grid_set(brooke_stats, 7, 0, "Alden");
        ds_grid_set(brooke_stats, 7, 1, "Cia");
        ds_grid_set(brooke_stats, 7, 2, "Lincoln");
        ds_grid_set(brooke_stats, 7, 3, "Sloane");
        ds_grid_set(brooke_stats, 7, 4, "Benji");
        ds_grid_set(brooke_stats, 7, 5, "Sara");
        ds_grid_set(brooke_stats, 7, 6, "Samara");
        ds_grid_set(brooke_stats, 7, 7, "Ford");
        ds_grid_set(brooke_stats, 7, 8, "Monroe");
        ds_grid_set(brooke_stats, 7, 9, "Wren");
        ds_grid_set(sophia_stats, 7, 0, "Alden");
        ds_grid_set(sophia_stats, 7, 1, "Bianca");
        ds_grid_set(sophia_stats, 7, 2, "Sloane");
        ds_grid_set(sophia_stats, 7, 3, "Benji");
        ds_grid_set(sophia_stats, 7, 4, "Caius");
        ds_grid_set(sophia_stats, 7, 5, "Helena");
        ds_grid_set(sophia_stats, 7, 6, "Monroe");
        ds_grid_set(sophia_stats, 7, 7, "Faust");
        ds_grid_set(sophia_stats, 7, 8, "Fenton");
        ds_grid_set(sophia_stats, 7, 9, "Rose");
        ds_grid_set(alexa_stats, 7, 0, "Cia");
        ds_grid_set(alexa_stats, 7, 1, "Lincoln");
        ds_grid_set(alexa_stats, 7, 2, "Bianca");
        ds_grid_set(alexa_stats, 7, 3, "Monroe");
        ds_grid_set(alexa_stats, 7, 4, "Iris");
        ds_grid_set(alexa_stats, 7, 5, "Maeve");
        ds_grid_set(alexa_stats, 7, 6, "Wren");
        ds_grid_set(alexa_stats, 7, 7, "Faust");
        ds_grid_set(alexa_stats, 7, 8, "Rose");
        ds_grid_set(alexa_stats, 7, 9, "Liberty");
        ds_grid_set(lincoln_stats, 7, 0, "Irving");
        ds_grid_set(lincoln_stats, 7, 1, "Garrick");
        ds_grid_set(lincoln_stats, 7, 2, "Bianca");
        ds_grid_set(lincoln_stats, 7, 3, "Brooke");
        ds_grid_set(lincoln_stats, 7, 4, "Sara");
        ds_grid_set(lincoln_stats, 7, 5, "Vesta");
        ds_grid_set(lincoln_stats, 7, 6, "Maeve");
        ds_grid_set(lincoln_stats, 7, 7, "Wren");
        ds_grid_set(lincoln_stats, 7, 8, "Fenton");
        ds_grid_set(lincoln_stats, 7, 9, "Alexa");
        ds_grid_set(iris_stats, 7, 0, "Maren");
        ds_grid_set(iris_stats, 7, 1, "Elias");
        ds_grid_set(iris_stats, 7, 2, "Bianca");
        ds_grid_set(iris_stats, 7, 3, "Caius");
        ds_grid_set(iris_stats, 7, 4, "Vesta");
        ds_grid_set(iris_stats, 7, 5, "Monroe");
        ds_grid_set(iris_stats, 7, 6, "Thae'Lanel");
        ds_grid_set(iris_stats, 7, 7, "Faust");
        ds_grid_set(iris_stats, 7, 8, "Rose");
        ds_grid_set(iris_stats, 7, 9, "Alexa");
        ds_grid_set(faust_stats, 7, 0, "Garrick");
        ds_grid_set(faust_stats, 7, 1, "Alden");
        ds_grid_set(faust_stats, 7, 2, "Sophia");
        ds_grid_set(faust_stats, 7, 3, "Sloane");
        ds_grid_set(faust_stats, 7, 4, "Benji");
        ds_grid_set(faust_stats, 7, 5, "Monroe");
        ds_grid_set(faust_stats, 7, 6, "Iris");
        ds_grid_set(faust_stats, 7, 7, "Fenton");
        ds_grid_set(faust_stats, 7, 8, "Rose");
        ds_grid_set(faust_stats, 7, 9, "Alexa");
        ds_grid_set(vesta_stats, 7, 0, "Irving");
        ds_grid_set(vesta_stats, 7, 1, "Elias");
        ds_grid_set(vesta_stats, 7, 2, "Lincoln");
        ds_grid_set(vesta_stats, 7, 3, "Corvan");
        ds_grid_set(vesta_stats, 7, 4, "Helena");
        ds_grid_set(vesta_stats, 7, 5, "Aurima");
        ds_grid_set(vesta_stats, 7, 6, "Ford");
        ds_grid_set(vesta_stats, 7, 7, "Iris");
        ds_grid_set(vesta_stats, 7, 8, "Maeve");
        ds_grid_set(vesta_stats, 7, 9, "Liberty");
        ds_grid_set(thaelanel_stats, 7, 0, "Elias");
        ds_grid_set(thaelanel_stats, 7, 1, "Sloane");
        ds_grid_set(thaelanel_stats, 7, 2, "Sara");
        ds_grid_set(thaelanel_stats, 7, 3, "Samara");
        ds_grid_set(thaelanel_stats, 7, 4, "Corvan");
        ds_grid_set(thaelanel_stats, 7, 5, "Helena");
        ds_grid_set(thaelanel_stats, 7, 6, "Aurima");
        ds_grid_set(thaelanel_stats, 7, 7, "Ford");
        ds_grid_set(thaelanel_stats, 7, 8, "Iris");
        ds_grid_set(thaelanel_stats, 7, 9, "Maeve");
        ds_grid_set(wren_stats, 7, 0, "Garrick");
        ds_grid_set(wren_stats, 7, 1, "Lincoln");
        ds_grid_set(wren_stats, 7, 2, "Bianca");
        ds_grid_set(wren_stats, 7, 3, "Brooke");
        ds_grid_set(wren_stats, 7, 4, "Caius");
        ds_grid_set(wren_stats, 7, 5, "Samara");
        ds_grid_set(wren_stats, 7, 6, "Maeve");
        ds_grid_set(wren_stats, 7, 7, "Rose");
        ds_grid_set(wren_stats, 7, 8, "Alexa");
        ds_grid_set(wren_stats, 7, 9, "Liberty");
        ds_grid_set(liberty_stats, 7, 0, "Irving");
        ds_grid_set(liberty_stats, 7, 1, "Sara");
        ds_grid_set(liberty_stats, 7, 2, "Corvan");
        ds_grid_set(liberty_stats, 7, 3, "Helena");
        ds_grid_set(liberty_stats, 7, 4, "Aurima");
        ds_grid_set(liberty_stats, 7, 5, "Vesta");
        ds_grid_set(liberty_stats, 7, 6, "Ford");
        ds_grid_set(liberty_stats, 7, 7, "Maeve");
        ds_grid_set(liberty_stats, 7, 8, "Wren");
        ds_grid_set(liberty_stats, 7, 9, "Alexa");
        ds_grid_set(helena_stats, 7, 0, "Maren");
        ds_grid_set(helena_stats, 7, 1, "Cia");
        ds_grid_set(helena_stats, 7, 2, "Elias");
        ds_grid_set(helena_stats, 7, 3, "Sophia");
        ds_grid_set(helena_stats, 7, 4, "Caius");
        ds_grid_set(helena_stats, 7, 5, "Aurima");
        ds_grid_set(helena_stats, 7, 6, "Vesta");
        ds_grid_set(helena_stats, 7, 7, "Thae'Lanel");
        ds_grid_set(helena_stats, 7, 8, "Rose");
        ds_grid_set(helena_stats, 7, 9, "Liberty");
        ds_grid_set(samara_stats, 7, 0, "Maren");
        ds_grid_set(samara_stats, 7, 1, "Elias");
        ds_grid_set(samara_stats, 7, 2, "Bianca");
        ds_grid_set(samara_stats, 7, 3, "Brooke");
        ds_grid_set(samara_stats, 7, 4, "Sara");
        ds_grid_set(samara_stats, 7, 5, "Corvan");
        ds_grid_set(samara_stats, 7, 6, "Aurima");
        ds_grid_set(samara_stats, 7, 7, "Ford");
        ds_grid_set(samara_stats, 7, 8, "Thae'Lanel");
        ds_grid_set(samara_stats, 7, 9, "Wren");
        ds_grid_set(sara_stats, 7, 0, "Irving");
        ds_grid_set(sara_stats, 7, 1, "Lincoln");
        ds_grid_set(sara_stats, 7, 2, "Sloane");
        ds_grid_set(sara_stats, 7, 3, "Brooke");
        ds_grid_set(sara_stats, 7, 4, "Caius");
        ds_grid_set(sara_stats, 7, 5, "Samara");
        ds_grid_set(sara_stats, 7, 6, "Corvan");
        ds_grid_set(sara_stats, 7, 7, "Aurima");
        ds_grid_set(sara_stats, 7, 8, "Thae'Lanel");
        ds_grid_set(sara_stats, 7, 9, "Liberty");
    }
}
