#!/usr/bin/env bash

# Exit immediately if a command exits with a non-zero status,
# treat unset variables as an error, and catch pipeline failures.
set -euo pipefail

# Script global variables
SCRIPT_NAME=$(basename "$0")
VERSION="3.0.0"
VERBOSE=false
APPID="1374840"
GAME_DIR=""
ACTION=""
OVERRIDE=false

# Get the directory where the script is located
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SCRIPTS_DIR="$BASE_DIR/scripts"

# Default install locations for Steam
STEAM_ROOTS=(
    "$HOME/.local/share/Steam"
    "$HOME/.steam/steam"
)

load_hashes() {
	if [[ ! -d "$SCRIPTS_DIR" ]]; then
    	echo "Error: \"$SCRIPTS_DIR\" directory not found."
    	exit 1
	fi
	
	local hash_file="$SCRIPTS_DIR/hashes.csv"
	if [[ ! -f "$hash_file" ]]; then
		prePatchHash=""
		postPatchHash=""
    	echo "Hash file not present.  Version validation will be skipped." >&2
	else
		# Read hashes from CSV
		prePatchHash=$(awk -F'"' '$2=="prePatch" {print $4}' "$hash_file")
		postPatchHash=$(awk -F'"' '$2=="postPatch" {print $4}' "$hash_file")
	fi
}

# Display usage instructions
usage() {
    cat << EOF
Dark Deity Community Patch installation and removal tool for Linux

This patch should support SteamOS, Ubuntu, and most other x86-based 
Linux distributions.  The patch is for Dark Deity version 1.5.8.

Usage: 
  ./${SCRIPT_NAME} COMMAND [FLAGS] [directory]
COMMAND can be one of
  -h, -?, --help  Show this help	
  -i, --install   Install the patch
  -u, --uninstall Uninstall the patch
  -c, --hash      Calculate the hash of data.win and data.win.old if it exists
FLAGS can be one or more of
  -o, --override    Ignore pre-patch validation failures and patch anyway
	
[directory] optionally specifies the directory of the Dark Deity executable 

Examples:
./${SCRIPT_NAME} -i
./${SCRIPT_NAME} -i "$HOME/.steam/steam/steamapps/common/Dark Deity"
./${SCRIPT_NAME} -u ~/.steam/steam/steamapps/common/"Dark Deity"
./${SCRIPT_NAME} --hash "/usr/games/Dark Deity"
EOF
}

find_libraryfolders_vdf() {
    for root in "${STEAM_ROOTS[@]}"; do
        if [[ -f "$root/steamapps/libraryfolders.vdf" ]]; then
            echo "$root/steamapps/libraryfolders.vdf"
            return 0
        fi
    done
    return 1
}

get_library_paths() {
    local vdf="$1"

    # Extract all "path" entries
    grep -E '^[[:space:]]*"path"' "$vdf" |
    sed -E 's/.*"path"[[:space:]]*"([^"]+)".*/\1/' |
    sed 's#\\\\#/#g'
}

find_game_dir() {
    local appid="$1"
    local vdf

    vdf=$(find_libraryfolders_vdf) || {
        echo "Steam libraryfolders.vdf not found" >&2
        return 1
    }

    while IFS= read -r library; do
        local steamapps="$library/steamapps"
        local manifest="$steamapps/appmanifest_${appid}.acf"
        local installdir

        if [[ -f "$manifest" ]]; then
            installdir=$(grep '"installdir"' "$manifest" |
                sed -E 's/.*"installdir"[[:space:]]*"([^"]+)".*/\1/')

            if [[ -n "$installdir" ]]; then
                echo "$steamapps/common/$installdir"
                return 0
            fi
        fi
    done < <(get_library_paths "$vdf")

    return 1
}

do_uninstall() {
    if [[ -f "${GAME_DIR}/data.win.old" ]]; then
        echo "--- Uninstalling existing patch ---"
        rm -f "${GAME_DIR}/data.win"
        mv "${GAME_DIR}/data.win.old" "${GAME_DIR}/data.win"
     	if [[ -f "$GAME_DIR/removepatch.sh" ]]; then
    		rm "$GAME_DIR/removepatch.sh"
    	fi
   	fi
}

do_install() {
    echo "--- Building patched.win ---"
    rm -f "$GAME_DIR/patched.win"
    $BASE_DIR/utmt_cli/UndertaleModCli load "$GAME_DIR/data.win" -s "$BASE_DIR/scripts/nongmlmods.csx" -s "$BASE_DIR/tools/scriptupdater.csx" -o "${GAME_DIR}/patched.win"
    echo "--- Renaming data.win to data.win.old to save as a backup ---"
    rm -f "$GAME_DIR/data.win.old"
    mv "$GAME_DIR/data.win" "$GAME_DIR/data.win.old"
    echo "--- Renaming patched.win to data.win ---"
    mv "$GAME_DIR/patched.win" "$GAME_DIR/data.win"	
    cp "$BASE_DIR/tools/removepatch.sh" "$GAME_DIR/removepatch.sh"              
}

do_version() {
    echo "$VERSION"
}

do_hash() {
	if [[ ! -f "$GAME_DIR/data.win" ]]; then
		echo "Error: Couldn't find file \"$GAME_DIR/data.win\""
		return 1
	fi
    local currentHash=$(get_sha256_hash "$GAME_DIR/data.win")
    echo "data.win: $currentHash"
    
	if [[ -f "$GAME_DIR/data.win.old" ]]; then		
    	local backupHash=$(get_sha256_hash "$GAME_DIR/data.win.old")
    	echo "data.win.old: $backupHash"
    fi
}

validate_gamedir() {
    if [[ -z "$GAME_DIR" ]]; then
        if ! GAME_DIR=$(find_game_dir "$APPID"); then
             cat << EOF >&2
Error: Failed to automatically locate the Dark Deity install folder.
If you can locate the directory, you can specify it manually.
Examples:
    ${SCRIPT_NAME} -i "$HOME/.steam/steam/steamapps/common/Dark Deity"
    ${SCRIPT_NAME} -u "/usr/games/steam/steamapps/common/Dark Deity"
EOF
            return 1
        fi    
    fi
    
    if [[ ! -f "$GAME_DIR/data.win" ]]; then
        echo "Error: file not found \"$GAME_DIR/data.win\""
        return 1
    fi
    
    echo "GAME_DIR = $GAME_DIR"
}

validate_prehash() {
	# If there's no hash to check against, then validation always succeeds
    if [[ -z "$prePatchHash" ]]; then
    	return 0
    fi
    
    # If data.win already matches the post hash then the patch is already installed
    local currentHash=$(get_sha256_hash "$GAME_DIR/data.win")
    if [[ "$currentHash" = "$postPatchHash" ]]; then
        echo "Patch was already installed.  Nothing to do."
        exit 0
    fi
	
	# If the data.win matches the pre-hash then we're ready to patch
    if [[ "$currentHash" = "$prePatchHash" ]]; then
        return 0
    fi
    
    # If the data.win file didn't have the right starting hash, check data.old.win
    local backupHash=""
    if [[ -f "$GAME_DIR/data.win.old" ]]; then
        backupHash=$(get_sha256_hash "$GAME_DIR/data.win.old")
    fi

    if [[ "$backupHash" = "$prePatchHash" ]]; then
        # if data.old.win is the right version, then run do_uninstall to restore data.win 
        # from it before starting the patch process
        do_uninstall
        return 0
    fi

	# Normally validation should fail here, but if the user wants to override validation then just allow patching data.win anyway, even though its not the version the patch was designed for.
    if [[ $OVERRIDE = true ]]; then
    	return 0
   	fi
        	
    # Neither data.win nor data.win.old is the right version and the user doesn't want to override, so the patch can't be applied.  Give some info and signal failure.
    echo "Expected pre-patch hash:  $prePatchHash"
    echo "Expected post-patch hash: $postPatchHash"
    echo "data.win hash:            $currentHash"
    if [[ -n "$backupHash" ]]; then
        echo "data.win.old hash:    $backupHash"
    fi
    echo "Error: Dark Deity version mismatch."
    echo "You can use the --override switch to force it to be applied."
    return 1
}

validate_posthash() {
	# If there's no hash or it is being overridden, then validation always succeeds
    if [[ -z "$postPatchHash" || $OVERRIDE = true ]]; then
		echo -e "\033[32mThe patch installation was successful.\033[0m"
    	return 0
    fi
		
	# Report whether the final hash matches the expected then end the script.
	local currentHash=$(get_sha256_hash "$GAME_DIR/data.win")
	if [[ "$currentHash" = "$postPatchHash" ]]; then
		echo "Post-patch hash validation passed."
		echo -e "\033[32mThe patch installation was successful.\033[0m"
		exit 0
	else	
		echo "Experted hash: $postPatchHash"
		echo "Actual hash: $currentHash"
		echo -e "\033[31mPost-patch hash validation failed.\033[0m"
		exit 1
	fi
}

get_sha256_hash() {
    sha256sum "$1" | awk '{print $1}'
}

set_action() {
    if [[ -n "$ACTION" ]]; then 
        echo "Error: More than one command specified in arguments." >&2
        return 1
    fi
    ACTION="$1"
}
       
# Main application logic
main() {
    case "$ACTION" in
        "install")
        	load_hashes
            validate_gamedir
            validate_prehash
            do_install
            validate_posthash
            ;;
        "uninstall")
            validate_gamedir
            if [[ ! -f "$GAME_DIR/data.win.old" ]]; then
                cat << EOF 
There is no backup file "$GAME_DIR/data.win.old".
Either:
   1) The patch was never installed.
   2) The patch was installed but it has already been uninstalled.
   3) The patch is still installed but you deleted the backup file.
If your problem is #3 then to uninstall you should:
   - Go to your Library in Steam
   - Right-click Dark Deity and select Properties->Installed Files
   - Click on Verify integrity of game files
   This will cause Steam to check the game files and re-download data.win if necesary.
EOF
            fi
            do_uninstall
            ;;
        "help")
            usage
            ;;
        "hash")
        	validate_gamedir
            do_hash
            ;;
        "version")
            do_version
            ;;
        *)
            echo "Internal error: No handler for command \"$ACTION\"" >&2
            return 1
            ;;
    esac
}


# Parse command-line arguments safely
parse_params() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            #  --- COMMANDS ---
            -h|-\?|--help)
                shift 
                set_action "help"
                ;; 
            -i|--install)
                shift
                set_action "install";
                ;;
            -u|--uninstall)
                shift
                set_action "uninstall";
                ;;
            -c|--hash)
                shift
                set_action "hash";
                ;;
            --version)
                shift
                set_action "version";
                ;;
                
            # --- OPTIONS ---
            # verbose is not currently used but it is implemented here for possible future use
            -v|--verbose)
                shift
                VERBOSE=true
                ;;
            -o|--override)
            	shift
            	OVERRIDE=true
            	;;
            -*)
                echo "Error: Unrecognized argument \"$1\"." >&2
                return 1
                ;;
            *)    
                if [[ -z "$ACTION" ]]; then
                    echo "Error: Command switch missing." >&2
                    return 1
                fi
                
                if [[ "$ACTION" = "install" || "$ACTION" = "uninstall" || "$ACTION" = "hash" ]]; then        
                    if [[ $# -gt 1 ]]; then
                        echo "Error: Optional path argument must be the last argument." >&2
                        echo "If you want use a path with a space in it, be sure to enclose it in quotation marks." >&2
                        return 1
                    fi

                    GAME_DIR="$1"
                else
                    echo "Error: Unexpected argument \"$1\"." >&2
                    return 1
                fi
                shift
                ;;
        esac
    done
}

# Script entry point
parse_params "$@"
if [[ -z "$ACTION" ]]; then
    usage
    exit 0
fi
main "$@"
